### ISSUE TITLE
set_v_max doesn't effect the ipOpt solver

### ISSUE THREAD

**Issue by towardthesea** [robotology-playground/react-control#15]
As I understand from the code [reactCtrlThread](https://github.com/robotology/react-control/blob/integration-planner/modules/reactController/src/reactCtrlThread.cpp#L123), the `vMax` effect the calculation of ipOpt through `vLimNominal` and `vLimAdapted`. However, at [setVMax](https://github.com/robotology/react-control/blob/integration-planner/modules/reactController/src/reactCtrlThread.cpp#L833), only `vMax` is updated, the rest remains unchanged. Trying to `yInfo` the value of `vLimAdapted` fed to `ipOpt solver` also shows that there is no effect.

**Comment by pattacini** [comment]
Good catch @towardthesea please correct the bug.

**Comment by pattacini** [comment]
Should be fixed via https://github.com/robotology/react-control/commit/7a53c282726229c7bd7db58d7245c8a392bb4da6; closing then.

**Comment by matejhof** [comment]
Thanks for bringing this up. 
The fix is IMO not completely correct though.

1. I would keep only the lines setting the `vLimNominal`. 

`vLimAdapted` is then set by the `avoidanceHandler` based on `vLimNominal` here:
https://github.com/robotology/react-control/blob/integration-planner/modules/reactController/src/reactCtrlThread.cpp#L605

2. The code disabling specific torso joints should not be repeated here:
https://github.com/robotology/react-control/blob/integration-planner/modules/reactController/src/reactCtrlThread.cpp#L845
Then the user will have to remember to change it at two places (used also here: https://github.com/robotology/react-control/blob/integration-planner/modules/reactController/src/reactCtrlThread.cpp#L134)
New way of disabling e.g. torso roll needs to be invented (config param) probably.

**Comment by towardthesea** [comment]
I don't agree with the 2nd point of `disable the torso` because if you don't repeat specify the torso when you setup the `vLimNominal` by that way, it will unintended release the motion of torso that we would like to block!
Anw, I don't have enough deep understand of this whole controller, so it can be considered as an temporary way to fix the bug.

**Comment by matejhof** [comment]
You're right - but exactly as you say. It is temporary and potentially dangerous as this disabling is now done at two places in the code by hand. 
But let's discuss this after the WYSIWYD party and in relation to https://github.com/robotology/react-control/issues/16
